spring:
  datasource:
    username: ${env.DATABASE_USERNAME}
    url: ${env.DATABASE_URL}
    password: ${env.DATABASE_PASSWORD}
  http:
    multipart:
      max-request-size: 11MB
      max-file-size: 10MB
  jackson:
    serialization:
      fail-on-empty-beans: "false"
  jpa:
    hibernate:
      ddl-auto: update
      logging:
        show-sql: true
    properties:
      hibernate:
        format_sql: true
security:
  jwt:
    ttlMillis: ${env.JWT_TTL_MILLIS}
    issuer: ${env.JWT_ISSUER}
    secret: ${env.JWT_SECRET}
cloud:
  aws:
    region:
      static: us-east-2
    stack:
      auto: false
    credentials:
      accessKey: ${env.AWS_ACCESS_KEY_ID}
      secretKey: ${env.AWS_SECRET_ACCESS_KEY}
logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataService: error
        util:
          EC2MetadataUtils: error
    org:
      springframework:
        web: DEBUG
servlet:
  multipart:
    max-request-size: ${env.MAX_REQUEST_SIZE}
    max-file-size: ${env.MAX_FILE_SIZE}
